// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// If env vars are missing, create a minimal mock supabase to avoid throwing during import
let _supabase: unknown;
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    'Supabase environment variables not found. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env and restart the dev server.'
  );

  const mockSubscription = { unsubscribe: () => {} };
  const mockAuth = {
    onAuthStateChange: (_cb: any) => ({ data: { subscription: mockSubscription } }),
    getSession: async () => ({ data: { session: null } }),
    signInWithPassword: async () => ({ error: new Error('Supabase not configured') }),
    signUp: async () => ({ error: new Error('Supabase not configured') }),
    signOut: async () => ({ error: new Error('Supabase not configured') }),
  };

  // Minimal mock object. Most DB operations will fail if used; this avoids a hard crash on import.
  _supabase = {
    auth: mockAuth,
    from: (_: string) => {
      throw new Error('Supabase client is not configured. Set env vars and restart the dev server.');
    },
  };
} else {
  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = _supabase as ReturnType<typeof createClient<Database>>;